
services:
  db:
    image: bitnami/postgresql:latest
    container_name: postgres-db
    restart: always
    env_file: .env
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data: